services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  # dashboard:
  #   image: metabase/metabase:latest
  #   ports:
  #     - "8001:3000"
  #   volumes:
  #     - ./data/metabase:/metabase-data
  #   environment:
  #     - JAVA_TIMEZONE=Europe/Berlin
  #     - MB_DB_FILE=/metabase-data/metabase.db
  #   depends_on:
  #     - db
  web:
    build: .
    volumes:
      - ./data/web:/data/input
      - ./data/logs:/data/logs
    ports:
      - "8000:8000"
    environment:
      - SIMPLE_EXP_DB__ENGINE=postgres
      - SIMPLE_EXP_DB__NAME=postgres
      - SIMPLE_EXP_DB__USER=postgres
      - SIMPLE_EXP_DB__PASSWORD=postgres
      - SIMPLE_EXP_DB__HOST=db
      - SIMPLE_EXP_DB__PORT=5432
      - "SIMPLE_EXP_SECRET_KEY=y2=2k%43!^jv_eecf*)e_3!psaz693q1syeq_6%4jm#c63-btl"
      - SIMPLE_EXP_DEBUG=true
      - 'SIMPLE_EXP_ALLOWED_HOSTS=["localhost"]'
      - SIMPLE_EXP_LANGUAGE_CODE=de-de
      - SIMPLE_EXP_TIME_ZONE=Europe/Berlin
      - SIMPLE_EXP_STATIC_ROOT=/app/static
      #- 'SIMPLE_EXP_CSRF_TRUSTED_ORIGINS=["https://simple-expenses.podewitz.local"]'
    depends_on:
      - db
