# Generated by Django 4.2.3 on 2023-07-27 08:34

from django.db import migrations, models
import django.db.models.deletion
import pendulum
import transactions.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_content_hash",
                    models.CharField(
                        blank=True, editable=False, max_length=64, null=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("iban", models.CharField(max_length=22, null=True, unique=True)),
                ("bic", models.CharField(max_length=11, null=True)),
                ("load_timestamp", models.DateTimeField(default=pendulum.now)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_content_hash",
                    models.CharField(
                        blank=True, editable=False, max_length=64, null=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("load_timestamp", models.DateTimeField(default=pendulum.now)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="transactions.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_content_hash",
                    models.CharField(
                        blank=True, editable=False, max_length=64, null=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("source", models.CharField(max_length=255, unique=True)),
                ("extract_timestamp", models.DateTimeField()),
                ("load_timestamp", models.DateTimeField(default=pendulum.now)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_content_hash",
                    models.CharField(
                        blank=True, editable=False, max_length=64, null=True
                    ),
                ),
                ("booking_date", models.DateField()),
                ("settlement_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=4, max_digits=22)),
                ("currency", models.CharField(max_length=3)),
                ("type", models.CharField(max_length=255, null=True)),
                ("purpose", models.TextField()),
                ("load_timestamp", models.DateTimeField(default=pendulum.now)),
                (
                    "category",
                    models.ForeignKey(
                        default=transactions.models.Category.get_unmapped_pk,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="transactions.category",
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="transactions.datasource",
                    ),
                ),
                (
                    "dst",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="transaction_dst_set",
                        to="transactions.account",
                    ),
                ),
                (
                    "src",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="transaction_src_set",
                        to="transactions.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="account",
            name="data_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="transactions.datasource",
            ),
        ),
    ]
