# Generated by Django 4.2.3 on 2023-08-08 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_transaction_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="load_timestamp",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="category",
            name="load_timestamp",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="load_timestamp",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="load_timestamp",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
