name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
#  pull_request:
#    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3
    - name: Get next version
      uses: reecetech/version-increment@2023.9.3
      id: version
      with:
        scheme: calver
        increment: patch
# TODO: create tag from new version and commit
    - name: Output Version
      env:
        NEXT_VERSION: ${{ steps.version.outputs.version }}
      run: echo "New Version $NEXT_VERSION"
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: "npodewitz/simple-expenses:${{ steps.version.outputs.version }}"
